-- The schema of the PostgreSQL dumps next to this file, made in postgres:18-alpine (database `shop`) with:
--   psql -U postgres -d shop < shop.postgres.sql
--   pg_dump -U postgres --schema-only shop > pg_dump-18-schema-only.sql
--   pg_dump -U postgres --schema-only --no-owner --no-privileges shop > pg_dump-18-schema-only-no-owner-no-privileges.sql
-- and, after a few rows in `users` and `products`,
--   pg_dump -U postgres --no-owner --no-privileges shop > pg_dump-18-with-data.sql
-- The dumps are the output of pg_dump as it is.

CREATE ROLE reporting;
CREATE SCHEMA app;
CREATE TYPE order_status AS ENUM ('new', 'paid', 'shipped', 'cancelled');
CREATE SEQUENCE invoice_number_seq START 1000;

CREATE TABLE users (
  id bigserial PRIMARY KEY,
  email text NOT NULL,
  name varchar(100),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_email_key UNIQUE (email)
);
COMMENT ON TABLE users IS 'Пользователи магазина';
COMMENT ON COLUMN users.email IS 'Адрес почты; уникален';
CREATE UNIQUE INDEX users_email_lower_idx ON users (lower(email));

CREATE TABLE products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sku varchar(32) NOT NULL UNIQUE,
  title text NOT NULL,
  price numeric(10,2) NOT NULL CHECK (price >= 0),
  tags text[] NOT NULL DEFAULT '{}'
);
CREATE INDEX products_tags_idx ON products USING gin (tags);

CREATE TABLE orders (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  status order_status NOT NULL DEFAULT 'new',
  invoice_number integer DEFAULT nextval('invoice_number_seq'),
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE INDEX orders_user_id_idx ON orders (user_id) WHERE deleted_at IS NULL;

CREATE TABLE order_items (
  order_id integer NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
  quantity integer NOT NULL DEFAULT 1,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE app.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES public.users (id) ON DELETE SET NULL,
  action text NOT NULL,
  payload jsonb,
  at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE measurements (
  id bigint NOT NULL,
  taken_on date NOT NULL,
  value double precision,
  PRIMARY KEY (id, taken_on)
) PARTITION BY RANGE (taken_on);
CREATE TABLE measurements_2026 PARTITION OF measurements FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');

CREATE VIEW active_orders AS SELECT * FROM orders WHERE deleted_at IS NULL;

CREATE FUNCTION touch_created_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.created_at := now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER orders_touch BEFORE INSERT ON orders FOR EACH ROW EXECUTE FUNCTION touch_created_at();

GRANT SELECT ON users, orders TO reporting;
GRANT USAGE ON SCHEMA app TO reporting;
